version: '3.5'
services:
  my-task:
    build:
      context: .
    container_name: my-task
    env_file:
      - docker_env.env
    command: tail -f /dev/null
    volumes:
      - .:/app
    logging:
      driver: json-file
